# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shunchuang', '0004_auto_20160521_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_class',
            field=models.IntegerField(default=1),
        ),
    ]
