# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shunchuang', '0010_auto_20160527_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='select',
            field=models.IntegerField(choices=[(1, b'chuangye'), (2, b'zudui')]),
        ),
    ]
