# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shunchuang', '0013_auto_20160527_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='select',
            field=models.IntegerField(choices=[(1, '\u521b\u4e1a'), (2, '\u7ec4\u961f')]),
        ),
    ]
