# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shunchuang', '0021_auto_20160529_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='person_photo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='head_portrait',
            field=models.ImageField(blank=True, null=True, upload_to=b'photos/%Y/%m'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='person_photo1',
            field=models.ImageField(blank=True, null=True, upload_to=b'photos/%Y/%m'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='person_photo2',
            field=models.ImageField(blank=True, null=True, upload_to=b'photos/%Y/%m'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='person_photo3',
            field=models.ImageField(blank=True, null=True, upload_to=b'photos/%Y/%m'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='person_photo4',
            field=models.ImageField(blank=True, null=True, upload_to=b'photos/%Y/%m'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='person_photo5',
            field=models.ImageField(blank=True, null=True, upload_to=b'photos/%Y/%m'),
        ),
    ]
