# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shunchuang', '0022_auto_20160601_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('\u7537', '\u7537'), ('\u5973', '\u5973')], max_length=4),
        ),
    ]
