# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shunchuang', '0023_auto_20160601_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_portrait',
            field=models.ImageField(default=None, null=True, upload_to=b'photos/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='person_photo1',
            field=models.ImageField(default=None, null=True, upload_to=b'photos/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='person_photo2',
            field=models.ImageField(default=None, null=True, upload_to=b'photos/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='person_photo3',
            field=models.ImageField(default=None, null=True, upload_to=b'photos/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='person_photo4',
            field=models.ImageField(default=None, null=True, upload_to=b'photos/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='person_photo5',
            field=models.ImageField(default=None, null=True, upload_to=b'photos/%Y/%m'),
        ),
    ]
